version: "3"

services:

  service:
    build:
      context: .

    ports:
      - "8000:8000"
    volumes:
      - ./:/service

    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata cars_list_db_data.json &&
             python manage.py runserver 0.0.0.0:8000"
