# Generated by Django 5.0 on 2024-01-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=63)),
                ("brand", models.CharField(max_length=63)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
